### ISSUE TITLE
Peer-review by Grace (Group 88)

### ISSUE THREAD

**Issue by gracenguyen133** [HaoboRrrr/USA_Election#4]
**1. Summary**

- The paper aims to forecast the upcoming U.S. Election, focusing on Kamala Harris’s support by analyzing polling data and the Dow Jones Industrial Average. The paper used a linear regression model to estimate the relationship between her support and Dow Jones Industrial Average values. The study highlights the correlation between economic indicators and electoral outcomes by utilizing visual tools to verify the predictions of the model.

**2. Strong positive points:**

- The paper is structured clearly and easy to follow.
- The reference list is updated.
- README is updated.
- The RProj file has been updated.
- LLM usage is included.
- There are sketches to support the model's prediction.

**3. Critical improvements needed:**

- Update README with more details such as the Overview section.
- Commit messages are not informative. 
- The RProj file name is not clear as right now it is "USA" only.
- LLM text is not updated properly even though it is included.
- Title is not complete.

**4. Suggestions for improvement:**

- Please update the README with a more complete Overview.
- Use informative messages when committing a change to your repo as right now it is not committed meaningfully.
- The file name of RProj should be clear and more informative.
- Please review the files and remove any original work from Rohan's starter folder, and update it properly for the current paper.
- Please update the LLM text to clearly state how AI is used in the paper.
- Update the Abstract to make it more informative by summarizing the key methods, findings, and significance of the paper.

**5. Evaluation:**

- R is appropriately cited: 0/1
- Data are appropriately cited: 0/1
- Class paper: 0/1
- LLM usage is documented: 0/1
- Title: 0/2 
- Author, date, and repo: 1/2
- Abstract: 1/4
- Introduction: 2/4
- Estimand: 0/1
- Data: 4/10
- Measurement: 1/4
- Model: 5/10
- Results: 0/10
- Discussion: 0/10
- Prose: 0/6
- Cross-references: 0/1
- Captions: 0/2
- Graphs/tables/etc: 1/4
- Idealized methodology: 0/10
- Idealized survey: 0/4
- Pollster methodology overview and evaluation: 0/10
- Referencing: 2/4
- Commits: 0/2
- Sketches: 0/2
- Simulation: 0/4
- Tests - simulation: 0/4
- Tests - actual: 0/4
- Parquet: 0/1
- Reproducible workflow: 2/4
- Miscellaneous: 1/3

**6. Estimated overall mark:**

- 20 out of 126.

**7. Any other comments:**

- Great work overall! I can see that the paper is on the right track as every part is structured clearly. There are a few areas for improvements which could be complete before the due date. Good luck!

**Comment by HaoboRrrr** [comment]
Revised as commented
