### ISSUE TITLE
Note on answers to certain questions

### ISSUE THREAD

**Issue by UTDQi** [HaoboRrrr/USA_Election#6]
Below are some of the responses form Rohan regarding some of the questions for the paper that I have. Please take them into consideration when writing. If any of you have more questions, please ask Rohan and post the replies under this issue. 

## Note: response to certain questions

1. How much should we elaborate on model justification and derivation?
a)	and methodology derivation
1: Include the justification and derivation in appendix, for (a): include in revelent part and show off your knowledge.

2.	What do you expect for meaningful commit message? 
Add some more detail, for example "edit scripts" to "edit such and such scripts", "clean data" -> "clean polling data", etc.

**Comment by UTDQi** [comment]
Note: try to explain terms and refer to required reading in writing idealized survey part.

**Comment by HaoboRrrr** [comment]
Revised as commented
