### ISSUE TITLE
Comment regarding appendix 2: idealized methodology and survey

### ISSUE THREAD

**Issue by UTDQi** [HaoboRrrr/USA_Election#7]
_The proposed methodology is well-thought through, realistic and would achieve the goals.(10 points)_ 

_The survey should have an introductory section and include the details of a contact person. The survey questions should be well constructed and appropriate to the task. The questions should have an appropriate ordering. A final section should thank the respondent.(4 points)_

_In another appendix, please put together an idealized methodology and survey that you would run if you had a budget of $100K and the task of forecasting the US presidential election. You should detail the sampling approach that you would use, how you would recruit respondents, data validation, and any other relevant aspects of interest. Also be careful to address any poll aggregation or other features of your methodology. You should actually implement your survey using a survey platform like Google Forms. A link to this should be included in the appendix. Additionally, a copy of the survey should be included in the appendix._

Above are the requirement given. 
Comments:  
1.	Try to refer to class readings and discuss the drawback and benefits associated with the choices. You have referred to sampling techniques, do include references of where you learned these.
2. For the important question section, discuss why did you choose to have these questions, are they there to identify survey trolling, to identify coverage error , or what? 
Below are some relevant class readings:
a)	How to Run Surveys, ([Stantcheva 2023](https://tellingstorieswithdata.com/99-references.html#ref-Stantcheva2023)) (https://www.annualreviews.org/content/journals/10.1146/annurev-economics-091622-010157)
b)	Text book(https://tellingstorieswithdata.com/08-hunt.html#surveys)
Discuss by referring to these and possibly other materials and include citations in the paper/references.bib file

2. Part of the appendix may be clearer to be stated in full sentences. For example: you could change
“• Stratified Random Sampling: To replicate the national electorate, stratify the sample according to age, gender, race/ethnicity, education level, urban/rural domicile, and area”
To “We choose to use Stratified Random Sampling to replicate the national electorate, stratify the sample according to age, gender, race/ethnicity, education level, urban/rural domicile, and area”

3. Your survey link is in the qmd file but not in pdf file, please check to make sure the pdf displays everything according to your intention.

**Comment by HaoboRrrr** [comment]
Revised as commonted
